# Generated by Django 5.1.4 on 2025-01-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='counseling_type',
            field=models.CharField(choices=[('ACADEMIC', 'Academic Counseling'), ('CAREER', 'Career Counseling'), ('PERSONAL', 'Personal Counseling'), ('MENTAL', 'Mental Health Counseling')], default='ACADEMIC', max_length=10),
        ),
    ]
