# Generated by Django 5.1.4 on 2025-01-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_counselor_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
