# Generated by Django 5.1.1 on 2025-03-31 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_psychologicalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason_aggression', models.BooleanField(default=False)),
                ('reason_dramatic_change', models.BooleanField(default=False)),
                ('reason_bullying_victim', models.BooleanField(default=False)),
                ('reason_bullying_bully', models.BooleanField(default=False)),
                ('reason_self_injury', models.BooleanField(default=False)),
                ('reason_daydreams', models.BooleanField(default=False)),
                ('reason_anger_management', models.BooleanField(default=False)),
                ('reason_fighting', models.BooleanField(default=False)),
                ('reason_stealing', models.BooleanField(default=False)),
                ('reason_sexual_acting_out', models.BooleanField(default=False)),
                ('reason_peer_relationships', models.BooleanField(default=False)),
                ('reason_social_skills', models.BooleanField(default=False)),
                ('reason_family_concerns', models.BooleanField(default=False)),
                ('reason_cries_easily', models.BooleanField(default=False)),
                ('reason_self_image', models.BooleanField(default=False)),
                ('reason_personal_hygiene', models.BooleanField(default=False)),
                ('reason_lying', models.BooleanField(default=False)),
                ('reason_grief_loss', models.BooleanField(default=False)),
                ('reason_impulsive', models.BooleanField(default=False)),
                ('reason_always_tired', models.BooleanField(default=False)),
                ('reason_worried', models.BooleanField(default=False)),
                ('reason_sadness', models.BooleanField(default=False)),
                ('reason_scared', models.BooleanField(default=False)),
                ('reason_absenteeism', models.BooleanField(default=False)),
                ('reason_inattentive', models.BooleanField(default=False)),
                ('reason_disruptive', models.BooleanField(default=False)),
                ('reason_withdrawn', models.BooleanField(default=False)),
                ('reason_anxious', models.BooleanField(default=False)),
                ('reason_motivation', models.BooleanField(default=False)),
                ('reason_academics', models.BooleanField(default=False)),
                ('reason_study_skills', models.BooleanField(default=False)),
                ('reason_homework_completion', models.BooleanField(default=False)),
                ('reason_organization_skills', models.BooleanField(default=False)),
                ('reason_early_pregnancy', models.BooleanField(default=False)),
                ('reason_public_display_affection', models.BooleanField(default=False)),
                ('reason_other', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('referred_by_name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.student')),
                ('to_counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to='core.counselor')),
            ],
            options={
                'verbose_name': 'Counseling Referral',
                'verbose_name_plural': 'Counseling Referrals',
                'ordering': ['-date'],
            },
        ),
    ]
