# Generated by Django 5.1.1 on 2025-03-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_counselingreferral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselingreferral',
            name='to_counselor',
        ),
        migrations.AddField(
            model_name='counselingreferral',
            name='to_counselor_name',
            field=models.CharField(default='Guidance Counselor', max_length=255, verbose_name='To Guidance Counselor'),
        ),
    ]
