# Generated by Django 5.1.1 on 2025-03-31 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_counselingreferral_to_counselor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingSessionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_from', models.TimeField(verbose_name='Time From')),
                ('time_to', models.TimeField(verbose_name='Time To')),
                ('session_type', models.CharField(choices=[('individual', 'Individual Counseling'), ('group', 'Group Counseling'), ('career', 'Career Counseling'), ('academic', 'Academic Counseling'), ('crisis', 'Crisis Intervention'), ('other', 'Other')], default='individual', max_length=20)),
                ('other_session_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Session Type')),
                ('purpose', models.TextField(verbose_name='Purpose of Session')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='core.counselor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_certificates', to='core.student')),
            ],
            options={
                'verbose_name': 'Counseling Session Certificate',
                'verbose_name_plural': 'Counseling Session Certificates',
                'ordering': ['-date'],
            },
        ),
    ]
